# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
# * https://jasontaiworkspace.slack.com/apps/A0F81FP4N-travis-ci?next_id=0
# * https://docs.travis-ci.com/user/tutorial/
# * DANGER_GITHUB_API_TOKEN

osx_image: xcode11
language: objective-c
# xcode_workspace: Example/MDictParser.xcworkspace
# xcode_scheme: platform=iOS Simulator,name=iPhone XÊ€,OS=13.0

# cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
- bundle install
- mkdir -p test_output
script:
- bundle exec fastlane ci_test
- bundle exec danger
after_success:
- bash <(curl -s https://codecov.io/bash) -t 0eb495c2-c19c-4f90-a03a-29b504655a7b
- echo $TRAVIS_BRANCH
notifications:
  slack: $SLACK_KEY
  email: false
