# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
# * https://jasontaiworkspace.slack.com/apps/A0F81FP4N-travis-ci?next_id=0
# * https://docs.travis-ci.com/user/tutorial/
# * DANGER_GITHUB_API_TOKEN

osx_image: xcode11
language: objective-c
# xcode_workspace: Example/MDictParser.xcworkspace
# xcode_scheme: platform=iOS Simulator,name=iPhone XÊ€,OS=13.0

# podfile: PodfileCI
before_install:
- mv PodfileCI Podfile
- mkdir -p test_output
script:
- bundle exec fastlane ci_test
- bundle exec danger
after_success:
- echo $TRAVIS_BRANCH
notifications:
  slack: jasontaiworkspace:ZDkT4i5r4YIKLKxhu3GxhnO9
  email: false
